In [3]:
a = [16, 17, 4, 3, 5, 2]
leaders = []

for i in range(len(a)):
    if a[i] == max(a[i:]):
        leaders.append(a[i])

print("Leader numbers:", leaders)

Leader numbers: [17, 5, 2]


In [6]:
def alternate_sort(arr):
    arr.sort()
    output = []
    i, j = 0, len(arr) - 1
    while i <= j:
        output.append(arr[i])
        if i != j:
            output.append(arr[j])
        i += 1
        j -= 1
    return output
input_array = [3, 1, 4, 1, 5, 8, 2, 6, 5, 1, 9, 3, 4]
result = alternate_sort(input_array)
print(result)

[1, 9, 1, 8, 1, 6, 2, 5, 3, 5, 3, 4, 4]


In [2]:
def find_three_numbers(arr, target_sum):
    n = len(arr)
    arr.sort()
    for i in range(n - 2):
        left, right = i + 1, n - 1
        while left < right:
            current_sum = arr[i] + arr[left] + arr[right]
            if current_sum == target_sum:
                return [arr[i], arr[left], arr[right]]
            elif current_sum < target_sum:
                left += 1
            else:
                right -= 1
    return []
arr = [1, 2, 3, 4, 5]
target_sum = int(input("enter the sum: "))
result = find_three_numbers(arr, target_sum)
if result:
    print("Three triplets are:", result)
else:
    print("No such triplet found.")

enter the sum: 9
Three triplets are: [1, 3, 5]


In [5]:
def sort_array(arr):
    counts = [0] * (max(arr) + 1)
    for num in arr:
        counts[num] += 1
    sorted_array = []
    for i in range(len(counts)):
        sorted_array.extend([i] * counts[i])
    return sorted_array
input_array = [0, 0, 1, 2, 0, 1, 2, 2, 1]
result = sort_array(input_array)
print(result)

[0, 0, 0, 1, 1, 1, 2, 2, 2]


In [9]:
a=[1,10,11,12,11,1,9,8,7,9]
b =[]
for i in range(len(a)-1):
        if a[i]!=a[i+1]:
            b.append(a[i])
            c = set(b)
print(c)

{1, 7, 8, 9, 10, 11, 12}


In [11]:
class ListNode:
    def __init__(self, value):
        self.value = value
        self.next = None
def has_loop(head):
    tortoise = head
    hare = head
    while hare is not None and hare.next is not None:
        tortoise = tortoise.next
        hare = hare.next.next          
        if tortoise == hare:
            return True 
    return False 
node1 = ListNode(1)
node2 = ListNode(2)
node3 = ListNode(3)
node4 = ListNode(4)
node1.next = node2
node2.next = node3
node3.next = node4
node4.next = node2 
result = has_loop(node1)
print(result)

True


In [52]:
def merge_sort(arr):
    if len(arr) > 1:
        mid = len(arr) // 2  
        left_half = arr[:mid]  
        right_half = arr[mid:]
        merge_sort(left_half)  
        merge_sort(right_half)
        i, j, k = 0, 0, 0
        while i < len(left_half) and j < len(right_half):
            if left_half[i] < right_half[j]:
                arr[k] = left_half[i]
                i += 1
            else:
                arr[k] = right_half[j]
                j += 1
            k += 1
        while i < len(left_half):
            arr[k] = left_half[i]
            i += 1
            k += 1
        while j < len(right_half):
            arr[k] = right_half[j]
            j += 1
            k += 1
input_array = [38, 27, 43, 3, 9, 82, 10]
merge_sort(input_array)
print("Sorted array:", input_array)

Sorted array: [3, 9, 10, 27, 38, 43, 82]


In [44]:
def max_sum(arr):
    if not arr:
        return 0

    max_sum = current_sum = arr[0]

    for num in arr[1:]:
        current_sum = max(num, current_sum + num)
        max_sum = max(max_sum, current_sum)

    return max_sum

arr = [1, -3, 4, -2, -1, 6]
print("Maximum sum of an arr:",max_sum(arr) )

Maximum sum of an arr: 7


In [19]:
import numpy as np
values = [0,1,2,3,4,5,6,7,8]
x = np.array(values).reshape(3, 3)
print(x)
print("")
for i in range(3):
    for j in range(3):
        x[0][0],x[0][2] = x[0][2],x[0][0] 
        x[2][0],x[2][2] = x[2][2],x[2][0]
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[2 1 0]
 [3 4 5]
 [8 7 6]]


In [21]:
def find_indices(arr, target):
    indices = []
    for i in range(len(arr)):
        if arr[i] == target:
            indices.append(i)
    return indices
input_array = [4, 2, 7, 1, 4, 5, 4, 9]
target_number = 4
result = find_indices(input_array, target_number)
if result:
    print(f"The indices of {target_number} in the array are: {result}")
else:
    print(f"{target_number} is not present in the array.")

The indices of 4 in the array are: [0, 4, 6]


In [55]:
matrix = [[1, 0, 1, 1],
          [1, 1, 1, 1],
          [1, 0, 1, 0],
          [1, 0, 0, 1]]
def mostones(matrix):
    max_ones = 0
    row_index = -1
    for i, row in enumerate(matrix):
        count_ones = row.count(1)
        if count_ones > max_ones:
            max_ones = count_ones
            row_index = i
    return row_index
print("Row index with the most ones:",mostones(matrix) )

Row index with the most ones: 1


In [51]:
import numpy as py
x = [1,2,3,4,5,6,7,8,9]
matrix = py.array(x).reshape(3, 3)
print(matrix)
rows = len(matrix)
columns = len(matrix[0])
if rows % 2 != 0 and columns % 2 != 0:
    middle_row = rows // 2
    middle_column = columns // 2
    sum_middle_row = sum(matrix[middle_row])
    sum_middle_column = sum(row[middle_column] for row in matrix)
print(f"Sum of the middle row: {sum_middle_row}")
print(f"Sum of the middle column: {sum_middle_column}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of the middle row: 15
Sum of the middle column: 15


In [33]:
import numpy as py
x = [7,6,5,1,2,3,8,4,9]
y = np.array(x).reshape(3, 3)
print(y)
for i in range(len(x)):
    min_index = i
    for j in range(i + 1, len(x)):
        if x[j] < x[min_index]:
            min_index = j
    if min_index != i:
        x[i], x[min_index] = x[min_index], x[i]
z = np.array(x).reshape(3, 3)
print(z)
for i in range(3):
    for j in range(3):
        if i == j:
            y[i][j] = 0
        elif((i==0 and j==2) or (i==2 and j==0)):
            y[i][j] = 0
a = np.array(y).reshape(3,3)
print(a)

[[7 6 5]
 [1 2 3]
 [8 4 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0 6 0]
 [1 0 3]
 [0 4 0]]


In [35]:
a = int(input("Enter your first number: "))
b = int(input("Enter your second number: "))
def multiply(x, y):
    if y == 0:
        return 0
    if y > 0:
        return x + multiply(x, y - 1)
    if y < 0:
        return - multiply(x, -y)
result = multiply(a,b)
print(result) 

Enter your first number: -33
Enter your second number: -15
495


In [37]:
class Node:
    def __init__ (self,value):
        self.value = value
        self.left = None
        self.right = None
def search_bst(root,ele):
    if root is None:
        return False
    if root.value == ele:
        return True
    if ele < root.value:
        return search_bst(root.left, ele)
    else:
        return search_bst(root.right, ele)
root = Node(10)
root.left = Node(8)
root.right = Node(20)
root.left.left = Node(7)
root.left.right = Node(9)
root.right.left = Node(15)
root.right.right = Node(21)
ele = int(input("Enter the elements to search for: "))
found = search_bst(root,ele)
if found:
    print("Found".format(ele))
else:
    print("Not found". format(ele))

Enter the elements to search for: 20
Found


In [39]:
class Node:
    def __init__ (self,value):
        self.value = value
        self.left = None
        self.right = None
def sumofleafnodes(root):
    if root is None:
        return 0
    elif root.left is None and root.right is None:
        return root.value
    return sumofleafnodes(root.left) + sumofleafnodes(root.right)
root = Node(10)
root.left = Node(8)
root.right = Node(20)
root.left.left = Node(7)
root.left.right = Node(9)
root.right.left = Node(15)
root.right.right = Node(21)
sum = sumofleafnodes(root)
print("The sum of all leaf nodes is ",format(sum))

The sum of all leaf nodes is  52


In [41]:
class Node:
    def __init__(self, key):
        self.data = key
        self.left = None
        self.right = None
def printSpiral(root):
    if root is None:
        return
    stack1 = []  
    stack2 = []  
    stack1.append(root)  # Start with the root node
    while stack1 or stack2:
        while stack1:
            node = stack1.pop()
            print(node.data, end=" ")

            if node.left:
                stack2.append(node.left)
            if node.right:
                stack2.append(node.right)
        while stack2:
            node = stack2.pop()
            print(node.data, end=" ")
            if node.right:
                stack1.append(node.right)
            if node.left:
                stack1.append(node.left)
root = Node(1)
root.left = Node(2)
root.right = Node(3)
root.left.left = Node(4)
root.left.right = Node(5)
root.right.left = Node(6)
root.right.right = Node(7)
root.left.left.left = Node(8)
root.left.left.right = Node(9)
root.left.right.left = Node(10)
root.left.right.right = Node(11)
root.right.left.left = Node(12)
root.right.left.right = Node(13)
root.right.right.left = Node(14)
root.right.right.right = Node(15)
print("Spiral Order traversal of the BST:")
printSpiral(root)

Spiral Order traversal of the BST:
1 3 2 4 5 6 7 15 14 13 12 11 10 9 8 